\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Modelos lineares aula 1},
            pdfauthor={Danilo de Paula Santos/Gabriela Wunsch Lopes},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Modelos lineares aula 1}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Danilo de Paula Santos/Gabriela Wunsch Lopes}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{17/10/2019}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# install.packages("compareGroups")}
\CommentTok{# install.packages("ggplot2")}
\CommentTok{# install.packages("data.table")}


\KeywordTok{library}\NormalTok{(}\StringTok{"compareGroups"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(}\StringTok{"ggplot2"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(}\StringTok{"haven"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(}\StringTok{"ggpubr"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(}\StringTok{"dplyr"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{suwit-dataset}{%
\section{Suwit dataset}\label{suwit-dataset}}

\hypertarget{estudo-da-relacao-entre-infeccao-por-ancilostomo-e-perda-de-sangue.-tailandia-1970}{%
\subsection{Estudo da relação entre infecção por ancilóstomo e perda de
sangue. Tailândia
1970}\label{estudo-da-relacao-entre-infeccao-por-ancilostomo-e-perda-de-sangue.-tailandia-1970}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{suwit <-}\StringTok{ }\KeywordTok{read_sav}\NormalTok{(}\StringTok{"Bancos/Suwit.sav"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{primeiro-passo-verificar-o-banco}{%
\paragraph{Primeiro passo: verificar o
banco}\label{primeiro-passo-verificar-o-banco}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{compare_suwit <-}\StringTok{ }\KeywordTok{compareGroups}\NormalTok{( }\OperatorTok{~}\StringTok{ }\NormalTok{., }\DataTypeTok{data =}\NormalTok{ suwit)}

\KeywordTok{summary}\NormalTok{(compare_suwit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  --- Descriptives of each row-variable ---
## 
## ------------------- 
## row-variable: Identificação 
## 
##       N  mean sd       lower    upper   
## [ALL] 15 8    4.472136 5.523414 10.47659
## 
## ------------------- 
## row-variable: número de vermes 
## 
##       N  mean  sd       lower    upper   
## [ALL] 15 552.4 513.9007 267.8113 836.9887
## 
## ------------------- 
## row-variable: Perda de sangue por dia 
## 
##       N  mean     sd       lower    upper   
## [ALL] 15 33.45267 24.85249 19.68982 47.21551
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabela_suwit <-}\StringTok{ }\KeywordTok{createTable}\NormalTok{(compare_suwit)}

\NormalTok{tabela_suwit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## --------Summary descriptives table ---------
## 
## ______________________________________ 
##                            [ALL]    N  
##                            N=15        
## ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ 
## Identificação           8.00 (4.47) 15 
## número de vermes         552 (514)  15 
## Perda de sangue por dia 33.5 (24.9) 15 
## ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
\end{verbatim}

\hypertarget{segundo-passo-verificar-linearidade-com-grafico-de-dispersao-e-identificar-pontos}{%
\paragraph{Segundo passo: verificar linearidade com gráfico de dispersão
e identificar
pontos}\label{segundo-passo-verificar-linearidade-com-grafico-de-dispersao-e-identificar-pontos}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\tightlist
\item
  Gráfico de dispersão
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{suwit_scatter <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(suwit, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ vermes, }\DataTypeTok{y =}\NormalTok{ perda_sangue))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_x_continuous}\NormalTok{(}\StringTok{"Número de vermes"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\StringTok{"Perda de sangue por um dia"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_minimal}\NormalTok{()}

\NormalTok{suwit_scatter}
\end{Highlighting}
\end{Shaded}

\includegraphics{Aula1_RegSimples_files/figure-latex/suwit_scatter-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  Identificando pontos: qual o ID do ponto mais extremo na vertical?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{suwit }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(perda_sangue}\OperatorTok{>}\DecValTok{75}\NormalTok{, vermes}\OperatorTok{<}\DecValTok{1500}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##      id vermes perda_sangue
##   <dbl>  <dbl>        <dbl>
## 1    13   1012         86.7
\end{verbatim}

\hypertarget{terceiro-passo-estimar-modelo}{%
\paragraph{Terceiro passo: estimar
modelo}\label{terceiro-passo-estimar-modelo}}

Modelo liner para perda de sangue em função de número de vermes

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm_suwit <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{formula =}\NormalTok{ perda_sangue }\OperatorTok{~}\StringTok{ }\NormalTok{vermes,}
                    \DataTypeTok{data =}\NormalTok{ suwit)}

\KeywordTok{summary}\NormalTok{(lm_suwit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = perda_sangue ~ vermes, data = suwit)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -15.846 -10.812   0.750   4.356  34.390 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 10.847327   5.308569   2.043   0.0618 .  
## vermes       0.040922   0.007147   5.725 6.99e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 13.74 on 13 degrees of freedom
## Multiple R-squared:  0.716,  Adjusted R-squared:  0.6942 
## F-statistic: 32.78 on 1 and 13 DF,  p-value: 6.99e-05
\end{verbatim}

Gerando intervalo de confiança para os parâmetros estimados

Intervalo de confiança: estima quanto, em média, é a perda sanguínea de
um grupo de pacientes com determinado número de vermes

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{confint}\NormalTok{(lm_suwit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                   2.5 %      97.5 %
## (Intercept) -0.62113883 22.31579336
## vermes       0.02548089  0.05636321
\end{verbatim}

A cada aumento de 1 verme, ocorre um aumento de 0.04 (95\%IC 0.026 -
0.056) na perda de sangue, sendo que 71,6\% (Multiple R-squared) da
variabilidade da perda de sangue em relação à perda média da amostra é
explicada pelo aumento do número de vermes.

Estimando intervalo de predição para cada observação do banco

Intervalo de predição: prediz a perda de sangue para um paciente que
apresenta determinado número de vermes

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{suwit_pred <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(lm_suwit, }\DataTypeTok{interval =} \StringTok{'predict'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in predict.lm(lm_suwit, interval = "predict"): predictions on current data refer to _future_ responses
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{suwit_pred}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         fit        lwr       upr
## 1  12.15683 -19.543164  43.85683
## 2  14.48939 -16.999013  45.97779
## 3  14.61216 -16.865752  46.09006
## 4  15.51244 -15.890490  46.91537
## 5  19.85018 -11.241030  50.94139
## 6  20.17755 -10.893500  51.24861
## 7  21.44614  -9.551347  52.44362
## 8  32.33140   1.663860  62.99895
## 9  33.14984   2.485006  63.81468
## 10 35.15502   4.483672  65.82638
## 11 38.75616   8.026311  69.48602
## 12 48.12731  16.966765  79.28786
## 13 52.26044  20.785321  83.73556
## 14 53.97917  22.351510  85.60682
## 15 89.78596  52.474437 127.09748
\end{verbatim}

Incluindo o intervalo de predição para cada observação do banco

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{suwit <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(suwit, suwit_pred)}
\end{Highlighting}
\end{Shaded}

Gerando um gráfico contendo intervalo de confiança e intervalo de
predição

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{suwit_pred_plot <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(suwit, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ vermes, }\DataTypeTok{y =}\NormalTok{ perda_sangue)) }\OperatorTok{+}
\StringTok{                                 }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{                                 }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{) }\OperatorTok{+}
\StringTok{                                 }\KeywordTok{scale_x_continuous}\NormalTok{(}\StringTok{"Número de vermes"}\NormalTok{) }\OperatorTok{+}
\StringTok{                                 }\KeywordTok{scale_y_continuous}\NormalTok{(}\StringTok{"Perda de sangue por um dia"}\NormalTok{) }\OperatorTok{+}
\StringTok{                                 }\KeywordTok{theme_minimal}\NormalTok{() }\OperatorTok{+}
\StringTok{                                 }\KeywordTok{geom_line}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ lwr), }\DataTypeTok{col =} \StringTok{"coral2"}\NormalTok{, }\DataTypeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\OperatorTok{+}
\StringTok{                                 }\KeywordTok{geom_line}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ upr), }\DataTypeTok{col =} \StringTok{"coral2"}\NormalTok{, }\DataTypeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \KeywordTok{paste}\NormalTok{(}\StringTok{"Adj R2 = "}\NormalTok{,}\KeywordTok{signif}\NormalTok{(}\KeywordTok{summary}\NormalTok{(lm_suwit)}\OperatorTok{$}\NormalTok{adj.r.squared, }\DecValTok{5}\NormalTok{),}
                         \StringTok{"Intercept ="}\NormalTok{,}\KeywordTok{signif}\NormalTok{(lm_suwit}\OperatorTok{$}\NormalTok{coef[[}\DecValTok{1}\NormalTok{]],}\DecValTok{5}\NormalTok{ ),}
                         \StringTok{" Slope ="}\NormalTok{,}\KeywordTok{signif}\NormalTok{(lm_suwit}\OperatorTok{$}\NormalTok{coef[[}\DecValTok{2}\NormalTok{]], }\DecValTok{5}\NormalTok{),}
                         \StringTok{" p ="}\NormalTok{,}\KeywordTok{signif}\NormalTok{(}\KeywordTok{summary}\NormalTok{(lm_suwit)}\OperatorTok{$}\NormalTok{coef[}\DecValTok{2}\NormalTok{,}\DecValTok{4}\NormalTok{], }\DecValTok{5}\NormalTok{)))}
  
  
  
  
\NormalTok{suwit_pred_plot}
\end{Highlighting}
\end{Shaded}

\includegraphics{Aula1_RegSimples_files/figure-latex/full_plot_suwit-1.pdf}

A faixa cinza corresponde ao intervalo de confiança e as linhas laranja
são os limites do intervalo de predição.

\hypertarget{fat_dat-dataset}{%
\section{Fat\_dat dataset}\label{fat_dat-dataset}}

\hypertarget{estudo-fat_dat-fitting-percentage-of-body-fat-to-simple-body-measurements}{%
\subsection{Estudo Fat\_dat ``Fitting Percentage of Body Fat to Simple
Body
Measurements''}\label{estudo-fat_dat-fitting-percentage-of-body-fat-to-simple-body-measurements}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fat_dat <-}\StringTok{ }\KeywordTok{read_sav}\NormalTok{(}\StringTok{"Bancos/fat_dat.sav"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Corrigindo os erros de digitação:

\begin{itemize}
\tightlist
\item
  The body densities for cases 48, 76, and 96, for instance, each seem
  to have one digit in error as can be seen from the two body fat
  percentage values.
\item
  Case 42) over 200 pounds in weight who is less than 3 feet tall (the
  height should presumably be 69.5 inches, not 29.5 inches)!
\item
  The percent body fat estimates are truncated to zero when negative
  (case 182)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Altura}

\NormalTok{fat_dat}\OperatorTok{$}\NormalTok{altura_pol <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{( fat_dat}\OperatorTok{$}\NormalTok{numero }\OperatorTok{==}\StringTok{ }\DecValTok{42}\NormalTok{, }\FloatTok{69.5}\NormalTok{, fat_dat}\OperatorTok{$}\NormalTok{altura_pol)}

\CommentTok{# Densidades}

\NormalTok{fat_dat}\OperatorTok{$}\NormalTok{densidade <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{( fat_dat}\OperatorTok{$}\NormalTok{numero }\OperatorTok{==}\StringTok{ }\DecValTok{48}\NormalTok{, }\FloatTok{1.0865}\NormalTok{, fat_dat}\OperatorTok{$}\NormalTok{densidade)}
\NormalTok{fat_dat}\OperatorTok{$}\NormalTok{densidade <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{( fat_dat}\OperatorTok{$}\NormalTok{numero }\OperatorTok{==}\StringTok{ }\DecValTok{76}\NormalTok{, }\FloatTok{1.0566}\NormalTok{, fat_dat}\OperatorTok{$}\NormalTok{densidade)}
\NormalTok{fat_dat}\OperatorTok{$}\NormalTok{densidade <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{( fat_dat}\OperatorTok{$}\NormalTok{numero }\OperatorTok{==}\StringTok{ }\DecValTok{96}\NormalTok{, }\FloatTok{1.0591}\NormalTok{, fat_dat}\OperatorTok{$}\NormalTok{densidade)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{compare_fat <-}\StringTok{ }\KeywordTok{compareGroups}\NormalTok{( }\OperatorTok{~}\StringTok{ }\NormalTok{., }\DataTypeTok{data =}\NormalTok{ fat_dat)}

\KeywordTok{summary}\NormalTok{(compare_fat)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  --- Descriptives of each row-variable ---
## 
## ------------------- 
## row-variable: numero 
## 
##       N   mean  sd       lower    upper   
## [ALL] 252 126.5 72.89033 117.4569 135.5431
## 
## ------------------- 
## row-variable: fat_Brozek 
## 
##       N   mean     sd       lower    upper  
## [ALL] 252 18.93849 7.750856 17.97689 19.9001
## 
## ------------------- 
## row-variable: fat_Siri 
## 
##       N   mean     sd      lower    upper   
## [ALL] 252 19.15079 8.36874 18.11253 20.18906
## 
## ------------------- 
## row-variable: densidade 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 1.055455 0.018909 1.053109 1.057801
## 
## ------------------- 
## row-variable: idade 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 44.88492 12.60204 43.32146 46.44838
## 
## ------------------- 
## row-variable: Peso em libras 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 178.9244 29.38916 175.2783 182.5706
## 
## ------------------- 
## row-variable: altura_pol 
## 
##       N   mean     sd       lower    upper  
## [ALL] 252 70.30754 2.609583 69.98378 70.6313
## 
## ------------------- 
## row-variable: kg/m2 
## 
##       N   mean    sd       lower   upper   
## [ALL] 252 25.4369 3.648111 24.9843 25.88951
## 
## ------------------- 
## row-variable: peso da massa magra 
## 
##       N   mean     sd       lower   upper   
## [ALL] 252 143.7139 18.23164 141.452 145.9758
## 
## ------------------- 
## row-variable: Circunferencia do pescoço 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 37.99206 2.430913 37.69047 38.29365
## 
## ------------------- 
## row-variable: Circunferencia do peito 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 100.8242 8.430476 99.77829 101.8701
## 
## ------------------- 
## row-variable: Circ do abdomem 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 92.55595 10.78308 91.21816 93.89375
## 
## ------------------- 
## row-variable: circ do quadril 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 99.90476 7.164058 99.01596 100.7936
## 
## ------------------- 
## row-variable: circ do coxa 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 59.40595 5.249952 58.75462 60.05728
## 
## ------------------- 
## row-variable: circ do joelho 
## 
##       N   mean     sd       lower    upper  
## [ALL] 252 38.59048 2.411805 38.29126 38.8897
## 
## ------------------- 
## row-variable: circ do tornozelo 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 23.10238 1.694893 22.89211 23.31266
## 
## ------------------- 
## row-variable: circ do biceps 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 32.27341 3.021274 31.89858 32.64825
## 
## ------------------- 
## row-variable: circ do antebraco 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 28.66389 2.020691 28.41319 28.91458
## 
## ------------------- 
## row-variable: circ do pulso 
## 
##       N   mean     sd       lower    upper   
## [ALL] 252 18.22976 0.933585 18.11394 18.34559
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabela_fat <-}\StringTok{ }\KeywordTok{createTable}\NormalTok{(compare_fat)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(compare_fat)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-1.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-2.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-3.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-4.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-5.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-6.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-7.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-8.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-9.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-10.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-11.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-12.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-13.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-14.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-15.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-16.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-17.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-18.pdf}
\includegraphics{Aula1_RegSimples_files/figure-latex/normalidade_fat_dat-19.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{disp_fat_Brozek<-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(fat_dat, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ imc, }\DataTypeTok{y =}\NormalTok{ fat_Brozek))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_minimal}\NormalTok{()}

\NormalTok{disp_fat_Brozek}
\end{Highlighting}
\end{Shaded}

\includegraphics{Aula1_RegSimples_files/figure-latex/dispersao_fat_Brozek-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm_imc_brozek <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{formula =}\NormalTok{ fat_Brozek }\OperatorTok{~}\StringTok{ }\NormalTok{imc,}
                    \DataTypeTok{data =}\NormalTok{ fat_dat)}

\KeywordTok{summary}\NormalTok{(lm_imc_brozek)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = fat_Brozek ~ imc, data = fat_dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -21.4292  -3.4478   0.2113   3.8663  11.7826 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -20.40508    2.36723   -8.62 7.78e-16 ***
## imc           1.54671    0.09212   16.79  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.324 on 250 degrees of freedom
## Multiple R-squared:   0.53,  Adjusted R-squared:  0.5281 
## F-statistic: 281.9 on 1 and 250 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{confint}\NormalTok{(lm_imc_brozek)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  2.5 %    97.5 %
## (Intercept) -25.067331 -15.74283
## imc           1.365275   1.72815
\end{verbatim}

A cada aumento de 1 unidade no IMC ocorre aumento de 1.55\% na gordura
corporal pelo índice Brozek. O intervalo de confiança é de 1.36 a 1.73.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{brozek_pred <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(lm_imc_brozek, }\DataTypeTok{interval =} \StringTok{"predict"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in predict.lm(lm_imc_brozek, interval = "predict"): predictions on current data refer to _future_ responses
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat_brozek <-}\KeywordTok{cbind}\NormalTok{(fat_dat, brozek_pred)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot_fat_Brozek <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(dat_brozek, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ imc, }\DataTypeTok{y =}\NormalTok{ fat_Brozek))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{ (}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{,)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_minimal}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_line}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ lwr), }\DataTypeTok{col =} \StringTok{"coral2"}\NormalTok{, }\DataTypeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\OperatorTok{+}\StringTok{   }\KeywordTok{geom_line}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ upr), }\DataTypeTok{col =} \StringTok{"coral2"}\NormalTok{, }\DataTypeTok{linetype =} \StringTok{"dashed"}\NormalTok{)}

\NormalTok{plot_fat_Brozek}
\end{Highlighting}
\end{Shaded}

\includegraphics{Aula1_RegSimples_files/figure-latex/regression_plot_fat_Brozek-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm_imc_siri <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{formula =}\NormalTok{ fat_Siri  }\OperatorTok{~}\StringTok{ }\NormalTok{imc,}
                    \DataTypeTok{data =}\NormalTok{ fat_dat)}

\KeywordTok{summary}\NormalTok{(lm_imc_siri)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = fat_Siri ~ imc, data = fat_dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -23.1070  -3.7418   0.2101   4.2070  12.8114 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -23.29940    2.55796  -9.109   <2e-16 ***
## imc           1.66884    0.09955  16.764   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 5.753 on 250 degrees of freedom
## Multiple R-squared:  0.5292, Adjusted R-squared:  0.5273 
## F-statistic:   281 on 1 and 250 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{confint}\NormalTok{(lm_imc_siri)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  2.5 %     97.5 %
## (Intercept) -28.337296 -18.261512
## imc           1.472787   1.864899
\end{verbatim}

Para o aumento de 1 ponto no IMC ocorre aumento de 1.7\% (95\%IC
1.5-1.86) na gordura corporal. O modelo explica 52\% da variabilidade da
gordura corporal.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{siri_pred <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(lm_imc_siri, }\DataTypeTok{interval =} \StringTok{"predict"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in predict.lm(lm_imc_siri, interval = "predict"): predictions on current data refer to _future_ responses
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dat_siri <-}\KeywordTok{cbind}\NormalTok{(fat_dat, siri_pred)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot_fat_siri <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(dat_siri, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ imc, }\DataTypeTok{y =}\NormalTok{ fat_Siri))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{ (}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{,)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_minimal}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_line}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ lwr), }\DataTypeTok{col =} \StringTok{"coral2"}\NormalTok{, }\DataTypeTok{linetype =} \StringTok{"dashed"}\NormalTok{) }\OperatorTok{+}\StringTok{   }\KeywordTok{geom_line}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ upr), }\DataTypeTok{col =} \StringTok{"coral2"}\NormalTok{, }\DataTypeTok{linetype =} \StringTok{"dashed"}\NormalTok{)}

\NormalTok{plot_fat_siri}
\end{Highlighting}
\end{Shaded}

\includegraphics{Aula1_RegSimples_files/figure-latex/regression_plot_fat_siri-1.pdf}

\hypertarget{anscombe-dataset}{%
\section{Anscombe dataset}\label{anscombe-dataset}}

\hypertarget{bancos-com-formas-funcionais-diferentes-mas-estatisticas-resumo-e-linhas-de-regressao-identicas}{%
\subsection{4 bancos com formas funcionais diferentes mas estatísticas
resumo e linhas de regressão
idênticas}\label{bancos-com-formas-funcionais-diferentes-mas-estatisticas-resumo-e-linhas-de-regressao-identicas}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{anscombe_dataset <-}\StringTok{ }\KeywordTok{data}\NormalTok{(}\StringTok{"anscombe"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{compare_anscombe <-}\StringTok{ }\KeywordTok{compareGroups}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ anscombe, }\OperatorTok{~}\StringTok{ }\NormalTok{x1}\OperatorTok{+}
\StringTok{                                     }\NormalTok{x2}\OperatorTok{+}
\StringTok{                                     }\NormalTok{x3}\OperatorTok{+}
\StringTok{                                     }\NormalTok{x4)}

\KeywordTok{createTable}\NormalTok{(compare_anscombe)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## --------Summary descriptives table ---------
## 
## _________________ 
##       [ALL]    N  
##       N=11        
## ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ 
## x1 9.00 (3.32) 11 
## x2 9.00 (3.32) 11 
## x3 9.00 (3.32) 11 
## x4 9.00 (3.32) 11 
## ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x1_scatter <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(anscombe, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ x1, }\DataTypeTok{y =}\NormalTok{ y1))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_minimal}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se =} \OtherTok{FALSE}\NormalTok{)}

\NormalTok{x1_scatter}
\end{Highlighting}
\end{Shaded}

\includegraphics{Aula1_RegSimples_files/figure-latex/anscombe_scatter_x1-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x2_scatter <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(anscombe, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ x2, }\DataTypeTok{y =}\NormalTok{ y2))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_minimal}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se =} \OtherTok{FALSE}\NormalTok{)}

\NormalTok{x2_scatter}
\end{Highlighting}
\end{Shaded}

\includegraphics{Aula1_RegSimples_files/figure-latex/anscombe_scatter_x2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x3_scatter <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(anscombe, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ x3, }\DataTypeTok{y =}\NormalTok{ y3))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_minimal}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se =} \OtherTok{FALSE}\NormalTok{)}

\NormalTok{x3_scatter}
\end{Highlighting}
\end{Shaded}

\includegraphics{Aula1_RegSimples_files/figure-latex/anscombe_scatter_x3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x4_scatter <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(anscombe, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ x4, }\DataTypeTok{y =}\NormalTok{ y4))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_minimal}\NormalTok{() }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se =} \OtherTok{FALSE}\NormalTok{)}

\NormalTok{x4_scatter}
\end{Highlighting}
\end{Shaded}

\includegraphics{Aula1_RegSimples_files/figure-latex/anscombe_scatter_x4-1.pdf}


\end{document}
